import { useContext, useEffect, useMemo, useState } from 'react'
import api from '../api/api'
import { RefreshCw, Cylinder, Plus } from 'lucide-react'
import { AuthContext } from '../context/AuthContext'
import SearchableSelect from '../components/SearchableSelect'

export default function EmptyCylinders() {
  const { user } = useContext(AuthContext)
  const [rows, setRows] = useState([]); const [loading, setLoading] = useState(true); const [quantities, setQuantities] = useState({}); const [error, setError] = useState('')
  const [items, setItems] = useState([]); const [shops, setShops] = useState([]); const [form, setForm] = useState({ shop_id: user?.shop_id || '', item_id: '', qty: '', note: '' })
  const gasItems = useMemo(() => items.filter(item => item.category_name?.toLowerCase().includes('gas')), [items])
  const load = async () => { setLoading(true); setError(''); try { const r = await api.get('/stocks/empty-cylinders'); setRows(r.data) } catch (e) { setError(e.response?.data?.msg || 'Unable to load empty cylinders. Please refresh the page.') } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  useEffect(() => { (async () => { try { const [itemsResponse, shopsResponse] = await Promise.all([api.get('/items'), api.get('/shops')]); setItems(itemsResponse.data); setShops(shopsResponse.data); if (!form.shop_id && shopsResponse.data.length) setForm(current => ({ ...current, shop_id: shopsResponse.data[0].id })) } catch { setError('Unable to load gas products and shops.') } })() }, [])
  const refill = async (row) => { const qty = Number(quantities[`${row.shop_id}-${row.item_id}`] || 0); if (!qty || qty > row.empty_qty) return alert('Enter a quantity within the available empty cylinders.'); try { await api.post('/stocks/empty-cylinders/refill', { shop_id: row.shop_id, item_id: row.item_id, qty }); await load() } catch (e) { alert(e.response?.data?.msg || 'Unable to refill cylinders') } }
  const addEmpties = async (e) => { e.preventDefault(); const qty = Number(form.qty); if (!form.shop_id || !form.item_id || !Number.isInteger(qty) || qty <= 0) return alert('Choose a shop and gas cylinder, then enter a whole positive quantity.'); try { await api.post('/stocks/empty-cylinders/add', { ...form, qty }); setForm(current => ({ ...current, item_id: '', qty: '', note: '' })); await load() } catch (e) { alert(e.response?.data?.msg || 'Unable to add empty cylinders') } }
  return <div>
    <div className="mb-6 flex items-center gap-3"><Cylinder className="text-amber-600" size={30}/><div><h1 className="text-2xl font-black">Empty Cylinders</h1><p className="text-sm text-gray-500">Add starting or newly acquired empties, then refill them into gas stock.</p></div></div>
    <form onSubmit={addEmpties} className="mb-6 rounded-2xl border border-gray-100 bg-white p-5 shadow-sm dark:border-gray-700 dark:bg-gray-800"><h2 className="mb-4 flex items-center gap-2 font-black"><Plus size={18} className="text-amber-600"/> Add empty cylinders</h2><div className="grid gap-3 md:grid-cols-4">{user?.role !== 'attendant' && <SearchableSelect options={shops} value={form.shop_id} onChange={e=>setForm({...form,shop_id:e.target.value})} placeholder="Choose shop..."/>}<SearchableSelect options={gasItems} value={form.item_id} onChange={e=>setForm({...form,item_id:e.target.value})} placeholder="Choose gas cylinder..."/><input className="rounded border p-3" type="number" min="1" step="1" value={form.qty} onChange={e=>setForm({...form,qty:e.target.value})} placeholder="Quantity"/><input className="rounded border p-3" value={form.note} onChange={e=>setForm({...form,note:e.target.value})} placeholder="Optional note"/></div><button className="mt-3 rounded-lg bg-amber-600 px-4 py-2 text-sm font-bold text-white">Add empties</button></form>
    <div className="overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-sm dark:border-gray-700 dark:bg-gray-800">
      {loading ? <div className="p-10 text-center text-gray-400">Loading empty cylinders...</div> : error ? <div className="p-10 text-center text-red-600">{error}</div> : rows.length === 0 ? <div className="p-10 text-center text-gray-400">No empty-cylinder records yet. Use the form above to enter each shop’s current balance.</div> : <div className="overflow-x-auto"><table className="w-full min-w-[650px]"><thead className="bg-gray-50 dark:bg-gray-900"><tr><th className="p-4 text-left text-xs uppercase text-gray-500">Shop</th><th className="p-4 text-left text-xs uppercase text-gray-500">Cylinder</th><th className="p-4 text-center text-xs uppercase text-gray-500">Empties</th><th className="p-4 text-center text-xs uppercase text-gray-500">Filled Stock</th><th className="p-4 text-center text-xs uppercase text-gray-500">Refill</th></tr></thead><tbody>{rows.map(row => { const key=`${row.shop_id}-${row.item_id}`; return <tr key={key} className="border-t dark:border-gray-700"><td className="p-4 font-semibold">{row.shop_name}</td><td className="p-4">{row.item_name}</td><td className="p-4 text-center font-black text-amber-600">{row.empty_qty}</td><td className="p-4 text-center font-bold">{row.filled_qty}</td><td className="p-4">{row.empty_qty > 0 && <div className="flex justify-center gap-2"><input className="w-20 rounded border p-2 text-center" type="number" min="1" max={row.empty_qty} value={quantities[key] || ''} onChange={e=>setQuantities({...quantities,[key]:e.target.value})}/><button onClick={()=>refill(row)} className="inline-flex items-center gap-1 rounded-lg bg-green-600 px-3 py-2 text-xs font-bold text-white"><RefreshCw size={14}/> Refill</button></div>}</td></tr>})}</tbody></table></div>}
    </div>
  </div>
}
