"""add receipt_uuid to deposit_payment model

Revision ID: 02d65c76a35a
Revises: 9dbe4ebd27bf
Create Date: 2025-11-21 13:14:09.132543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02d65c76a35a'
down_revision = '9dbe4ebd27bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deposit_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_uuid', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_deposit_payments_receipt_uuid'), ['receipt_uuid'], unique=False)
        batch_op.create_foreign_key('fk_deposit_payments_receipt_uuid', 'receipts', ['receipt_uuid'], ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deposit_payments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_deposit_payments_receipt_uuid', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_deposit_payments_receipt_uuid'))
        batch_op.drop_column('receipt_uuid')

    # ### end Alembic commands ###
