"""fix item_id foreign key in deposit_sales

Revision ID: 15ffe704d29d
Revises: c3ca0b16779e
Create Date: 2026-03-05 12:25:44.314581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ffe704d29d'
down_revision = 'c3ca0b16779e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deposit_sales', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_deposit_sales_item_id', 'items', ['item_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deposit_sales', schema=None) as batch_op:
        batch_op.drop_constraint('fk_deposit_sales_item_id', type_='foreignkey')

    # ### end Alembic commands ###
