"""add supplier_invoice_payments table

Revision ID: 195374fbbd4e
Revises: 1b120b4458fa
Create Date: 2026-03-05 11:49:19.231215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '195374fbbd4e'
down_revision = '1b120b4458fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_invoice_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['supplier_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_invoice_payments')
    # ### end Alembic commands ###
