"""remove sell_price from items and stocks

Revision ID: 1b120b4458fa
Revises: 38b82190424d
Create Date: 2026-03-05 10:28:47.756581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b120b4458fa'
down_revision = '38b82190424d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('sell_price')

    with op.batch_alter_table('shop_stocks', schema=None) as batch_op:
        batch_op.drop_column('sell_price')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=50), nullable=True))

    with op.batch_alter_table('shop_stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sell_price', sa.NUMERIC(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sell_price', sa.NUMERIC(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###
