"""add indexes for reporting performance

Revision ID: 2d0f05071353
Revises: 15ffe704d29d
Create Date: 2026-03-10 18:22:08.734653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d0f05071353'
down_revision = '15ffe704d29d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deposit_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deposit_payments_paid_on'), ['paid_on'], unique=False)

    with op.batch_alter_table('deposit_sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deposit_sales_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deposit_sales_shop_id'), ['shop_id'], unique=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_shop_id'), ['shop_id'], unique=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_shop_id'), ['shop_id'], unique=False)

    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfers_from_shop_id'), ['from_shop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transfers_to_shop_id'), ['to_shop_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfers_to_shop_id'))
        batch_op.drop_index(batch_op.f('ix_transfers_from_shop_id'))
        batch_op.drop_index(batch_op.f('ix_transfers_created_at'))

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_shop_id'))
        batch_op.drop_index(batch_op.f('ix_sales_created_at'))

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_shop_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_created_at'))

    with op.batch_alter_table('deposit_sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deposit_sales_shop_id'))
        batch_op.drop_index(batch_op.f('ix_deposit_sales_created_at'))

    with op.batch_alter_table('deposit_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deposit_payments_paid_on'))

    # ### end Alembic commands ###
