"""add stock batches for fifo tracking

Revision ID: 6f601b2ecbac
Revises: 2d0f05071353
Create Date: 2026-03-10 19:24:41.275196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f601b2ecbac'
down_revision = '2d0f05071353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('initial_qty', sa.Integer(), nullable=False),
    sa.Column('remaining_qty', sa.Integer(), nullable=False),
    sa.Column('buy_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_batches_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_batches_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_batches_remaining_qty'), ['remaining_qty'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_batches_shop_id'), ['shop_id'], unique=False)

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_sale_item_batch', 'stock_batches', ['batch_id'], ['id'])

    # Populate stock_batches from current shop_stocks
    connection = op.get_bind()
    # Use standard SQL to select from shop_stocks and insert into stock_batches
    shop_stocks = connection.execute(sa.text("SELECT shop_id, item_id, quantity, buy_price FROM shop_stocks WHERE quantity > 0 AND buy_price IS NOT NULL")).fetchall()
    
    from datetime import datetime
    now = datetime.utcnow()
    
    for ss in shop_stocks:
        connection.execute(
            sa.text("INSERT INTO stock_batches (shop_id, item_id, initial_qty, remaining_qty, buy_price, source_type, created_at) VALUES (:shop_id, :item_id, :quantity, :quantity, :buy_price, 'initial', :created_at)"),
            {"shop_id": ss.shop_id, "item_id": ss.item_id, "quantity": ss.quantity, "buy_price": ss.buy_price, "created_at": now}
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('batch_id')

    with op.batch_alter_table('stock_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_batches_shop_id'))
        batch_op.drop_index(batch_op.f('ix_stock_batches_remaining_qty'))
        batch_op.drop_index(batch_op.f('ix_stock_batches_item_id'))
        batch_op.drop_index(batch_op.f('ix_stock_batches_created_at'))

    op.drop_table('stock_batches')
    # ### end Alembic commands ###
