"""add notes to transfer model

Revision ID: 726e721897af
Revises: e0d69bdd1e5c
Create Date: 2025-11-21 13:09:22.005405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726e721897af'
down_revision = 'e0d69bdd1e5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfers', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
