"""add shop_id to supplier_invoice_items

Revision ID: 933c3b720453
Revises: 195374fbbd4e
Create Date: 2026-03-05 12:09:09.130311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '933c3b720453'
down_revision = '195374fbbd4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Set a default shop_id (1) for existing records
    op.execute('UPDATE supplier_invoice_items SET shop_id = 1 WHERE shop_id IS NULL')
    
    # Now make it NOT NULL and add FK
    with op.batch_alter_table('supplier_invoice_items', schema=None) as batch_op:
        batch_op.alter_column('shop_id', nullable=False)
        batch_op.create_foreign_key('fk_supplier_invoice_items_shop_id', 'shops', ['shop_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_invoice_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_supplier_invoice_items_shop_id', type_='foreignkey')
        batch_op.drop_column('shop_id')

    # ### end Alembic commands ###
