"""add receipt_uuid to sale model

Revision ID: 9dbe4ebd27bf
Revises: 726e721897af
Create Date: 2025-11-21 13:12:31.362771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dbe4ebd27bf'
down_revision = '726e721897af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_uuid', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_receipt_uuid'), ['receipt_uuid'], unique=False)
        batch_op.create_foreign_key('fk_sales_receipt_uuid', 'receipts', ['receipt_uuid'], ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sales_receipt_uuid', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sales_receipt_uuid'))
        batch_op.drop_column('receipt_uuid')

    # ### end Alembic commands ###
