"""Remove ItemSize model and add buy_price and sell_price to Item model

Revision ID: a796e27405c0
Revises: dae5bef26764
Create Date: 2025-11-21 23:51:25.882501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a796e27405c0'
down_revision = 'dae5bef26764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Manual recreation of shop_stocks table to drop item_size_id and its foreign key
    op.rename_table('shop_stocks', '_old_shop_stocks')
    op.create_table('shop_stocks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('shop_id', sa.Integer(), nullable=False),
        sa.Column('item_id', sa.Integer(), nullable=False),
        sa.Column('quantity', sa.Integer(), default=0),
        sa.Column('buy_price', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('sell_price', sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
        sa.ForeignKeyConstraint(['shop_id'], ['shops.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.execute('INSERT INTO shop_stocks (id, shop_id, item_id, quantity, buy_price, sell_price, updated_at) SELECT id, shop_id, item_id, quantity, buy_price, sell_price, updated_at FROM _old_shop_stocks')
    op.drop_table('_old_shop_stocks')

    with op.batch_alter_table('deposit_sales', schema=None) as batch_op:
        batch_op.drop_column('item_size_id')

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.drop_column('item_size_id')

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_column('item_size_id')

    with op.batch_alter_table('transfer_items', schema=None) as batch_op:
        batch_op.drop_column('item_size_id')

    op.drop_table('item_sizes')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buy_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('sell_price', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.drop_column('default_sell_price')
        batch_op.drop_column('default_buy_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_size_id', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_size_id', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('shop_stocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_size_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'item_sizes', ['item_size_id'], ['id'])

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_buy_price', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('default_sell_price', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.drop_column('sell_price')
        batch_op.drop_column('buy_price')

    op.create_table('item_sizes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=False),
    sa.Column('label', sa.VARCHAR(length=64), nullable=True),
    sa.Column('buy_price', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('sell_price', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
